#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | hello:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<help_content
    zzz <app>, Says "zzz <app>"
    zzz:zzzccc, Says "zzzccc"
help_content
    }

    if [[ $1 = "zzz:help" ]] ; then
        echo -e 'Usage: dokku hello[:world] [<app>]'
        echo ''
        echo 'Say zzz.'
        echo ''
        echo 'Example:'
        echo ''
        echo '$ dokku zzz:zzzccc'
        echo 'zzzccc'
        echo ''
        echo 'Additional commands:'
        help_content_func | sort | column -c2 -t -s,
    else
        help_content_func
    fi
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac